//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arrivals
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Arrivals()
        {
            this.ConsistArrival = new HashSet<ConsistArrival>();
        }
    
        public int NumberArrival { get; set; }
        public Nullable<int> ArrivalAccepted { get; set; }
        public int Suplier { get; set; }
        public System.DateTime ArrivalDate { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Supliers Supliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsistArrival> ConsistArrival { get; set; }
    }
}
