//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsistArrival
    {
        public int IDConsArrivals { get; set; }
        public int NumberArrival { get; set; }
        public int ItemNumber { get; set; }
        public int AmountArr { get; set; }
        public Nullable<double> VolumeArr { get; set; }
    
        public virtual Arrivals Arrivals { get; set; }
        public virtual BuildMaterials BuildMaterials { get; set; }
    }
}
