//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WarehouseEntities3 : DbContext
    {
        public WarehouseEntities3()
            : base("name=WarehouseEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Arrivals> Arrivals { get; set; }
        public virtual DbSet<BuildMaterials> BuildMaterials { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<ConsistArrival> ConsistArrival { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Ordered> Ordered { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Supliers> Supliers { get; set; }
        public virtual DbSet<UnitToMeasure> UnitToMeasure { get; set; }
    }
}
