//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordered
    {
        public int IDOrdered { get; set; }
        public int IDOrder { get; set; }
        public int ItemNumber { get; set; }
        public int AmountOrd { get; set; }
    
        public virtual BuildMaterials BuildMaterials { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
